on:
  pull_request:
    branches: [master, main, devl]
    paths-ignore:
    - '.github/**'
  repository_dispatch:
    types: [check_trigger]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', renv: '~\AppData\Local\renv'}
          - {os: ubuntu-22.04, r: 'release', renv: '~/.local/share/renv'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_RENV_CACHE_DIR: ${{ matrix.config.renv }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Fix path for Windows caching
        if: runner.os == 'Windows'
        shell: bash
        run: echo "C:/windows/System32" >> $GITHUB_PATH

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}
            ${{ env.R_RENV_CACHE_DIR }}
          key: ${{ matrix.config.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ matrix.config.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('meztez/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION', remotes = TRUE))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          if (file.exists("renv.lock")) {
            if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
            renv::restore()
          } else {
            remotes::install_deps(dependencies = TRUE)
          }
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
          if (file.exists("renv.lock")) {
            renv::diagnostics()
          }
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--no-multiarch"), error_on = "error", check_dir = "check")
        shell: Rscript {0}
  R-CMD-check-version:
    name: New version check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get latest pkgs list
        run: |
          curl \
          -X GET -f -O \
          -H "Authorization:token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3.raw" \
          -L https://api.github.com/repos/LaCapitale/dsops-r-minicran/contents/.github/pkgs.csv
      - name: Check if package version is greater than minicran
        shell: Rscript --no-init-file {0}
        run: |
          pkg <- read.dcf("DESCRIPTION")[,"Package"][[1]]
          new_v <- read.dcf("DESCRIPTION")[,"Version"][[1]]
          cur_v <- read.csv("pkgs.csv", row.names = 1)[pkg,]
          if (isTRUE(nchar(cur_v) > 0)) {
           if (utils::compareVersion(cur_v, new_v) > -1) {
            stop(pkg, " package build version ", new_v,
                 " is not greater than the current miniCRAN version ", cur_v,
                 ". Bump version in package DESCRIPTION file.")
           }
          } else {
           message("No current version found, probably a new package.")
          }
