on:
  push:
    branches: [main, master]

name: test

jobs:
  test:
    if:  github.ref_name != 'create-pull-request/patch' && github.actor != 'github-actions'
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release', renv: '~/.local/share/renv'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GIT_HUB_PAT_SECRET }}
      R_RENV_CACHE_DIR: ${{ matrix.config.renv }}
     
    steps:
      - name: Trigger doc workflow
        run: |
          echo "$GITHUB_PAT"
          touch run_ok
          if [[ -f "run_ok" ]]; then
            # Run curl -- https://stackoverflow.com/questions/38906626/curl-to-return-http-status-code-along-with-the-response
            http_response=$(curl -s -o response.txt -w "%{http_code}"  \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization:token $GITHUB_PAT" \
              https://api.github.com/repos/cgauvi/ben.R.utils/actions/workflows/41536288/dispatches \
              -d '{"ref":"master"}'
              )
              
            # Inspect reponse
            if [ $http_response != "200" ]; then
                echo $GITHUB_PAT
                cat response.txt >&2 
                exit 1
            fi
            # Remove tmp file that exists
            rm run_ok
          else
            printf '%s\n' "Couldnt manage to triger the documentation workflow" >&2 
            exit 1
          fi